# Generated by Django 4.2.16 on 2026-06-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('party_symbol', models.ImageField(blank=True, help_text='Party symbol image (PNG/SVG recommended)', null=True, upload_to='candidates/symbols/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/')),
                ('bio', models.TextField(blank=True, help_text='Short biography shown on ballot')),
                ('manifesto_points', models.TextField(blank=True, help_text='Key manifesto points (one per line)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order on ballot page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
